name: Release
on:
  push:
    branches: [main]
jobs:
  tag_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from version.txt
        id: get_version
        run: |
          TAG_NAME=$(cat version.txt)
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
      - name: Create a tag
        env:
          TAG_NAME: ${{ env.tag_name }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${process.env.TAG_NAME}`,
            sha: context.sha
            })
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
